#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zoraxy"
name = "Zoraxy"
description.en = "General purpose HTTP reverse proxy and forwarding tool"
description.fr = "Outil de proxy inverse et de transfert HTTP à usage général"

version = "3.2.9~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://zoraxy.aroz.org/"
admindoc = "https://github.com/tobychui/zoraxy/wiki/Getting-Started"
code = "https://github.com/tobychui/zoraxy"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "zoraxy"
    amd64.url = "https://github.com/tobychui/zoraxy/releases/download/v3.2.9/zoraxy_linux_amd64"
    amd64.sha256 = "033f6dd64c9de17c3d1042f625637ab05ef9cea09e096d3825cd5e7c03dcffc4"
    armhf.url = "https://github.com/tobychui/zoraxy/releases/download/v3.2.9/zoraxy_linux_arm"
    armhf.sha256 = "5bb9cd876f38e436925cb2084f03a9d27f5bb62c6dd2e8e97f87033748a6848d"
    arm64.url = "https://github.com/tobychui/zoraxy/releases/download/v3.2.9/zoraxy_linux_arm64"
    arm64.sha256 = "3bf0d0a36c9cc4993ac5f836daa41aed58d9b1cd9ccf01c2d964451accaff350"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "zoraxy_linux_amd64"
    autoupdate.asset.arm64 = "zoraxy_linux_arm64"
    autoupdate.asset.armhf = "zoraxy_linux_arm"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
